add light color scheme
same hue for colors as in dark scheme
remove colors display from aliases definitions as now common to both

diff --git a/colors/utilities/list_base_hex b/colors/utilities/list_base_hex
--- a/colors/utilities/list_base_hex
+++ b/colors/utilities/list_base_hex
@@ -2,6 +2,13 @@
 
 # list hexadecimal values of base colors
 
-BASE_COLORS_FILE="${0%/*}/../definitions/base"
+THEME="${1:-dark}"
+
+BASE_COLORS_FILE="${0%/*}/../definitions/base_${THEME}"
+
+if [ ! -f "${BASE_COLORS_FILE}" ]; then
+  printf "invalid theme '%s'\n" "${THEME}" >&2
+  exit 1
+fi
 
 sed -n 's/| base0[[:alnum:]] | #\([[:alnum:]]\+\) |.*/\1/p' "${BASE_COLORS_FILE}"
