make light the default color scheme
make list_base_hex script theme argument required
so that the default color scheme is only defined in one place

diff --git a/colors/utilities/list_base_hex b/colors/utilities/list_base_hex
--- a/colors/utilities/list_base_hex
+++ b/colors/utilities/list_base_hex
@@ -2,7 +2,12 @@
 
 # list hexadecimal values of base colors
 
-THEME="${1:-dark}"
+THEME="$1"
+
+if [ -z "${THEME}" ]; then
+  printf 'missing theme argument\n' >&2
+  exit 1
+fi
 
 BASE_COLORS_FILE="${0%/*}/../definitions/base_${THEME}"
 
