make zsh scripts POSIX compliant
except (for now):
- help relies on zsh run-help command
- tmux-env relies on zsh for running session scripts

diff --git a/packages/zsh/scripts/loop b/packages/zsh/scripts/loop
--- a/packages/zsh/scripts/loop
+++ b/packages/zsh/scripts/loop
@@ -1,8 +1,8 @@
-#!/usr/bin/env zsh
-
-COMMAND=${0:t}
+#!/bin/sh
 
 init_variables() {
+  COMMAND=${0##*/}
+
   RUN_COMMAND=
   COUNT=
   INTERVAL=0
@@ -27,25 +27,36 @@ usage() {
 
 
 error() {
-  [[ -z "$1" ]] || echo "${COMMAND}: $1"
+  [ -z "$1" ] || echo "${COMMAND}: $1"
   echo "Try '${COMMAND} --help' for more information."
   exit 1
 } >&2
 
 
+current_time_sec() {
+  # values with leading 0 are interpreted as octals
+  # which leads to issue with "08" and "09"
+  CUR_HOURS=$( date +%H )
+  CUR_MINUTES=$( date +%M )
+  CUR_SECONDS=$( date +%S )
+  echo $((
+    ${CUR_HOURS#0} * 3600 + ${CUR_MINUTES#0} * 60 + ${CUR_SECONDS#0}
+  ))
+}
+
+
 loop_command() {
-    local end_time=
-    [[ -n "${TIME}" ]] && end_time=$(( SECONDS + TIME ))
+    [ -n "${TIME}" ] && END_TIME=$(( $( current_time_sec ) + TIME ))
 
-    local run_count=0
+    RUN_COUNT=0
 
-    while : ; do
+    while true; do
       eval "${RUN_COMMAND}"
 
-      ((run_count+=1))
+      RUN_COUNT=$(( RUN_COUNT + 1 ))
 
-      [[ -n "${TIME}" && "${SECONDS}" -ge "${end_time}" ]] && return 0
-      [[ -n "${COUNT}" && "${run_count}" -ge "${COUNT}" ]] && return 0
+      [ -n "${TIME}" ] && [ "$( current_time_sec )" -ge "${END_TIME}" ] && return 0
+      [ -n "${COUNT}" ] && [ "${RUN_COUNT}" -ge "${COUNT}" ] && return 0
 
       sleep "${INTERVAL}"
     done
@@ -53,10 +64,10 @@ loop_command() {
 
 
 parse_options() {
-  while [[ "$#" -gt 0 ]]; do
+  while [ "$#" -gt 0 ]; do
     case "$1" in
       -c|--count)
-        [[ -n "$2" ]] || error 'Missing --count value'
+        [ -n "$2" ] || error 'Missing --count value'
         COUNT="$2"
         shift 2
         ;;
@@ -65,12 +76,12 @@ parse_options() {
         exit 0
         ;;
       -i|--interval)
-        [[ -n "$2" ]] || error 'Missing --interactive value'
+        [ -n "$2" ] || error 'Missing --interactive value'
         INTERVAL="$2"
         shift 2
         ;;
       -t|--time)
-        [[ -n "$2" ]] || error 'Missing --time value'
+        [ -n "$2" ] || error 'Missing --time value'
         TIME="$2"
         shift 2
         ;;
@@ -80,28 +91,28 @@ parse_options() {
     esac
   done
 
-  RUN_COMMAND="$@"
+  RUN_COMMAND="$*"
 }
 
 
 validate_options() {
-  if [[ -z "${COUNT}" && -z "${TIME}" ]]; then
+  if [ -z "${COUNT}" ] && [ -z "${TIME}" ]; then
     error 'you must specify at least --count or --time options'
   fi
 
-  if [[ -n "${COUNT}" && ! ${COUNT} =~ ^[1-9][0-9]*$ ]]; then
-    error 'count must be a strictly positive integer'
-  fi
+  case "${COUNT}" in
+    *[!0-9]*) error 'count must be an integer' ;;
+  esac
 
-  if [[ -n "${TIME}" && ! ${TIME} =~ ^[1-9][0-9]*$ ]]; then
-    error 'time must be a strictly positive integer'
-  fi
+  case "${TIME}" in
+    *[!0-9]*) error 'time must be an integer' ;;
+  esac
 
-  if [[ ! ${INTERVAL} =~ ^[0-9]+(\.[0-9]*)?$ ]]; then
-    error 'interval must be a number'
-  fi
+  case "${INTERVAL}" in
+    *[!0-9.]*) error 'interval must be an number' ;;
+  esac
 
-  if [[ -z "${RUN_COMMAND}" ]]; then
+  if [ -z "${RUN_COMMAND}" ]; then
     error 'no command to run'
   fi
 }
diff --git a/packages/zsh/scripts/tmux-env b/packages/zsh/scripts/tmux-env
--- a/packages/zsh/scripts/tmux-env
+++ b/packages/zsh/scripts/tmux-env
@@ -1,13 +1,10 @@
-#!/usr/bin/env zsh
-
-COMMAND=${0:t}
+#!/bin/sh
 
 init_variables() {
+  COMMAND=${0##*/}
+
   ENV_DIR_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/env/"
 
-  AVAILABLE_TARGETS=( $(
-    ls "${ENV_DIR_PATH}"
-  ) )
   BACKGROUND=false
 
   TARGET=
@@ -19,66 +16,52 @@ usage() {
   cat <<- EOF
 	usage: ${COMMAND} [<options>] <target> [<session>]
 
-	Start target tmux environment sessions
+	Start target tmux environment session
+	If no session is defined, a new empty one is created
 
 	Options:
 	  -b,  --background     launch in background, no attach
 	  -h,  --help           show this message only
-
-	Available targets: ${AVAILABLE_TARGETS}
-	If no session is defined, a new empty one is created
 	EOF
 }
 
 
 error() {
-  [[ -z "$1" ]] || echo "${COMMAND}: $1"
+  [ -z "$1" ] || echo "${COMMAND}: $1"
   echo "Try '${COMMAND} --help' for more information."
   exit 1
 } >&2
 
 
 is_session_present() {
-  local session_names="$1"
-  local session="$2"
-
-  for session_name in ${(f)session_names}; do
-    if [[ "${session}" = "${session_name}" ]]; then
-      return 0
-    fi
-  done
-
-  return 1
+  tmux -L "${TARGET}" list-sessions -F '#{session_name}' 2> /dev/null \
+    | grep -q "^${SESSION}$"
 }
 
 
 start_target_tmux_env() {
-  local session_names=$(
-    tmux -L "${TARGET}" list-sessions -F '#{session_name}' 2> /dev/null
-  )
-
-  if [[ -n "${SESSION}" ]]; then
-    if ! is_session_present "${session_names}" "${SESSION}"; then
-      local script_path="${ENV_DIR_PATH}/${TARGET}/${SESSION}.sh"
-      TMUX_ENV=yes zsh "${script_path}" "${TARGET}" "${SESSION}"
+  if [ -n "${SESSION}" ]; then
+    if ! is_session_present; then
+      SCRIPT_PATH="${ENV_DIR_PATH}/${TARGET}/${SESSION}.sh"
+      TMUX_ENV=yes zsh "${SCRIPT_PATH}" "${TARGET}" "${SESSION}"
     fi
   else
     SESSION='new'
-    if ! is_session_present "${session_names}" "${SESSION}"; then
+    if ! is_session_present; then
       TMUX_ENV=yes tmux -L "${TARGET}" new-session -d -s "${SESSION}"
     fi
   fi
 
   if ! $BACKGROUND; then
-    tmux -L "${TARGET}" attach-session -t "${SESSION}" &> /dev/null
+    tmux -L "${TARGET}" attach-session -t "${SESSION}" > /dev/null 2>&1
   else
-    tmux -L "${TARGET}" switch-client -t "${SESSION}" &> /dev/null
+    tmux -L "${TARGET}" switch-client -t "${SESSION}" > /dev/null 2>&1
   fi
 }
 
 
 parse_options() {
-  while [[ "$#" -gt 0 ]]; do
+  while [ "$#" -gt 0 ]; do
     case "$1" in
       -b|--background)
         BACKGROUND=true
@@ -94,26 +77,26 @@ parse_options() {
     esac
   done
 
-  if [[ $# -eq 0 ]]; then
-    error 'missing target'
-  fi
-
   TARGET="$1"
   SESSION="$2"
 }
 
 
 validate_options() {
-  if [[ -n "${TMUX}" ]]; then
+  if [ -n "${TMUX}" ]; then
     error "nested tmux env is not allowed"
   fi
 
-  if ! (( ${AVAILABLE_TARGETS[(Ie)${TARGET}]} )); then
+  if [ -z "${TARGET}" ]; then
+    error 'missing target'
+  fi
+
+  if [ ! -d "${ENV_DIR_PATH}/${TARGET}" ]; then
     error "invalid target ${TARGET}"
   fi
 
-  if [[ -n "${SESSION}" \
-     && ! -f "${ENV_DIR_PATH}/${TARGET}/${SESSION}.sh" ]]; then
+  if [ -n "${SESSION}" ] \
+     && [ ! -f "${ENV_DIR_PATH}/${TARGET}/${SESSION}.sh" ]; then
     error "invalid target's session ${SESSION}"
   fi
 }
