translate_shell script use language arguments instead of select menu
select menu was slow to read and use
add autocompletion file

diff --git a/packages/zsh/scripts/translate_shell b/packages/zsh/scripts/translate_shell
--- a/packages/zsh/scripts/translate_shell
+++ b/packages/zsh/scripts/translate_shell
@@ -10,7 +10,7 @@ init_variables() {
 
 usage() {
   cat << EOF
-usage: ${COMMAND} [<options>]
+usage: ${COMMAND} [<options>] source target
 
 Launch a translation interactive shell
 
@@ -20,73 +20,10 @@ EOF
 }
 
 
-select_languages() {
-  # display the options in one column
-  old_columns=$COLUMNS
-  export COLUMNS=1
-
-  PS3='Select translation option: '
-
-  choices=(
-    'English    -> Français'
-    'English    -> Nederlands'
-    'Français   -> English'
-    'Français   -> Nederlands'
-    'Nederlands -> English'
-    'Nederlands -> Français'
-    'manual'
-    'quit'
-  )
-
-  select choice in ${choices}; do
-    case $choice in
-      'English    -> Français')
-        SOURCE_LANGUAGE='en'
-        TARGET_LANGUAGE='fr'
-        break
-        ;;
-      'English    -> Nederlands')
-        SOURCE_LANGUAGE='en'
-        TARGET_LANGUAGE='nl'
-        break
-        ;;
-      'Français   -> English')
-        SOURCE_LANGUAGE='fr'
-        TARGET_LANGUAGE='en'
-        break
-        ;;
-      'Français   -> Nederlands')
-        SOURCE_LANGUAGE='fr'
-        TARGET_LANGUAGE='nl'
-        break
-        ;;
-      'Nederlands -> English')
-        SOURCE_LANGUAGE='nl'
-        TARGET_LANGUAGE='en'
-        break
-        ;;
-      'Nederlands -> Français')
-        SOURCE_LANGUAGE='nl'
-        TARGET_LANGUAGE='fr'
-        break
-        ;;
-      'manual')
-         echo -n 'source language code? '
-         read SOURCE_LANGUAGE
-         echo -n 'target language code? '
-         read TARGET_LANGUAGE
-         break
-         ;;
-      'quit')
-        break
-        ;;
-      *)
-        echo 'invalid option'
-        ;;
-    esac
-  done
-
-  COLUMNS=$old_columns
+error() {
+  [[ -z "$1" ]] || echo "${COMMAND}: $1" >&2
+  echo "Try '${COMMAND} --help' for more information."
+  exit 1
 }
 
 
@@ -102,16 +39,25 @@ parse_options() {
         ;;
     esac
   done
+
+  SOURCE_LANGUAGE="$1"
+  TARGET_LANGUAGE="$2"
+}
+
+
+validate_options() {
+  if [[ -z "${SOURCE_LANGUAGE}" ]]; then
+    error 'missing source language'
+  fi
+
+  if [[ -z "${TARGET_LANGUAGE}" ]]; then
+    error 'missing target language'
+  fi
 }
 
 
 init_variables
 parse_options "$@"
-
-select_languages
-
-if [[ -z "${SOURCE_LANGUAGE}" || -z "${TARGET_LANGUAGE}" ]]; then
-  exit
-fi
+validate_options
 
 trans --shell "${SOURCE_LANGUAGE}:${TARGET_LANGUAGE}"
