zsh scripts follow the same "usual" structure
except for a couple of them where it is not really necessary:
- no argument needed (bullshit_generator)
- validation done by subcommand (man)
- no validation needed (upside_down)

diff --git a/zsh/scripts/emoji_animate b/zsh/scripts/emoji_animate
--- a/zsh/scripts/emoji_animate
+++ b/zsh/scripts/emoji_animate
@@ -1,17 +1,52 @@
 #!/usr/bin/env zsh
 
-NAME="$1"
-EXTRA="${@:2}"
+COMMAND=${0:t}
+
+init_variables() {
+  AVAILABLE_EMOJIS=(
+    'fliptable'
+    'cool'
+    'shrug'
+    'disapprove'
+    'happygary'
+  )
+
+  NAME=
+  EXTRA=
+}
 
 
-function frame {
+usage() {
+  cat << EOF
+usage: ${COMMAND} [<options>] name [extra]
+
+Animate an emoji
+Some supports an extra optional text argument
+
+Options:
+  -h,  --help    show this message only
+
+Available emojis name: ${AVAILABLE_EMOJIS}
+EOF
+}
+
+
+error() {
+  [[ -z "$1" ]] || echo "$1" >&2
+  usage
+  exit 1
+}
+
+
+frame() {
   # put some whitespaces before
   # so that the cursor is not over the display
   echo -ne "    $1\033[0K\r"
   sleep 0.2
 }
 
-function fliptable {
+
+emoji_fliptable() {
   local text="$1"
   local upside_down_text=$( upside_down ${text} )
 
@@ -40,7 +75,8 @@ function fliptable {
   echo
 }
 
-function cool {
+
+emoji_cool() {
   frame '( •_•)'
   frame '( •_•)'
   frame '( •_•)'
@@ -52,7 +88,8 @@ function cool {
   echo
 }
 
-function shrug {
+
+emoji_shrug() {
   frame '_╭-(ツ)-╮_'
   frame '_╭-(ツ)-╮_'
   frame '_╭-(ツ)-╮_'
@@ -61,7 +98,8 @@ function shrug {
   echo
 }
 
-function disapprove {
+
+emoji_disapprove() {
   frame 'ʘ‿ʘ'
   frame 'ʘ‿ʘ'
   frame 'ʘ‿ʘ'
@@ -72,7 +110,8 @@ function disapprove {
   echo
 }
 
-function happygary {
+
+emoji_happygary() {
   frame 'ᕕ(ᐛ)ᕗ'
   frame 'ᕕ(ᐛ)ᕗ'
   frame 'ᕙ(ᐖ)ᕡ'
@@ -86,4 +125,38 @@ function happygary {
 }
 
 
-$NAME $EXTRA 2> /dev/null
+
+parse_options() {
+  while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+      -h|--help)
+        usage
+        exit 0
+        ;;
+      *)
+        break 2
+        ;;
+    esac
+  done
+
+  NAME="$1"
+  EXTRA="${@:2}"
+}
+
+
+validate_options() {
+  if [[ -z "${NAME}" ]]; then
+    error 'missing emoji name'
+  fi
+
+  if ! (( ${AVAILABLE_EMOJIS[(Ie)${NAME}]} )); then
+    error "invalid emoji name ${NAME}"
+  fi
+}
+
+
+init_variables
+parse_options "$@"
+validate_options
+
+emoji_$NAME $EXTRA
diff --git a/zsh/scripts/http_prompt_env b/zsh/scripts/http_prompt_env
--- a/zsh/scripts/http_prompt_env
+++ b/zsh/scripts/http_prompt_env
@@ -1,11 +1,63 @@
 #!/usr/bin/env zsh
 
-ENV_DIR_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/http-prompt/env/"
+COMMAND=${0:t}
 
-if [[ -n "$2" ]]; then
-  ENV_PATH="${ENV_DIR_PATH}/$1/$2.hp"
-else
-  ENV_PATH="${ENV_DIR_PATH}/$1.hp"
-fi
+init_variables() {
+  ENV_DIR_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/http-prompt/env"
 
-http-prompt --env "$ENV_PATH"
+  ENV_PATH=
+}
+
+
+usage() {
+  cat << EOF
+usage: ${COMMAND} [<options>] project [environment]
+
+Start http-prompt with a custom project environment
+
+Options:
+  -h,  --help    show this message only
+EOF
+}
+
+
+error() {
+  [[ -z "$1" ]] || echo "$1" >&2
+  usage
+  exit 1
+}
+
+
+parse_options() {
+  while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+      -h|--help)
+        usage
+        exit 0
+        ;;
+      *)
+        break 2
+        ;;
+    esac
+  done
+
+  if [[ -n "$2" ]]; then
+    ENV_PATH="${ENV_DIR_PATH}/$1/$2.hp"
+  else
+    ENV_PATH="${ENV_DIR_PATH}/$1.hp"
+  fi
+}
+
+
+validate_options() {
+  if [[ ! -f "${ENV_PATH}" ]]; then
+    error 'invalid project or environment'
+  fi
+}
+
+
+init_variables
+parse_options "$@"
+validate_options
+
+http-prompt --env "${ENV_PATH}"
diff --git a/zsh/scripts/mycli_env b/zsh/scripts/mycli_env
--- a/zsh/scripts/mycli_env
+++ b/zsh/scripts/mycli_env
@@ -1,5 +1,67 @@
 #!/usr/bin/env zsh
 
-# copy of mycli alias (didn't manage to load here)
-mycli --defaults-group-suffix=_mycli \
-  $( cat "${XDG_CONFIG_HOME:-$HOME/.config}/mycli/env/$1.mc" )
+COMMAND=${0:t}
+
+init_variables() {
+  ENV_DIR_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/mycli/env"
+
+  PROJECT=
+  ENV_PATH=
+}
+
+
+usage() {
+  cat << EOF
+usage: ${COMMAND} [<options>] project
+
+Start mycli with a custom project environment
+
+Options:
+  -h,  --help    show this message only
+EOF
+}
+
+
+error() {
+  [[ -z "$1" ]] || echo "$1" >&2
+  usage
+  exit 1
+}
+
+
+parse_options() {
+  while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+      -h|--help)
+        usage
+        exit 0
+        ;;
+      *)
+        break 2
+        ;;
+    esac
+  done
+
+  PROJECT="$1"
+}
+
+
+validate_options() {
+  if [[ -z "${PROJECT}" ]]; then
+    error 'missing project'
+  fi
+
+  ENV_PATH="${ENV_DIR_PATH}/${PROJECT}.mc"
+
+  if [[ ! -f "${ENV_PATH}" ]]; then
+    error 'invalid project'
+  fi
+}
+
+
+init_variables
+parse_options "$@"
+validate_options
+
+# copy of mycli alias (didn't manage to load it here)
+mycli --defaults-group-suffix=_mycli $( cat "${ENV_PATH}" )
diff --git a/zsh/scripts/pacman_pkgdiff b/zsh/scripts/pacman_pkgdiff
--- a/zsh/scripts/pacman_pkgdiff
+++ b/zsh/scripts/pacman_pkgdiff
@@ -1,28 +1,90 @@
 #!/usr/bin/env zsh
 
-PACKAGE_NAME="$1"
+COMMAND=${0:t}
 
-PACKAGE_VERSION=$(
-  pacman --query "${PACKAGE_NAME}" \
-    | cut --field 2 --delimiter ' '
-)
+init_variables() {
+  PACKAGE_NAME=
+}
 
-# need double --check argument to show modified files
-PACKAGE_MODIFIED_FILES=( $(
-  pacman --query --check --check "${PACKAGE_NAME}" \
-    | grep '^backup file:' \
-    | cut --field 4 --delimiter ' ' \
-    | uniq
-) )
 
-# if it happens we have packages with many modified files
-# we'll better extract first a single time instead of doing for each file
-for PACKAGE_MODIFIED_FILE in ${PACKAGE_MODIFIED_FILES}; do
-  echo "${PACKAGE_MODIFIED_FILE}"
-  tar --extract --to-stdout \
-    --file /var/cache/pacman/pkg/${PACKAGE_NAME}-${PACKAGE_VERSION}-*.pkg.tar.xz \
-    "${PACKAGE_MODIFIED_FILE/\//}" \
-    2> /dev/null \
-  | diff - "${PACKAGE_MODIFIED_FILE}"
-  echo
-done
+usage() {
+  cat << EOF
+usage: ${COMMAND} [<options>] package
+
+Display a diff of a package modified files
+
+Options:
+  -h,  --help    show this message only
+EOF
+}
+
+
+error() {
+  [[ -z "$1" ]] || echo "$1" >&2
+  usage
+  exit 1
+}
+
+
+diff_package() {
+  local package_version=$(
+    pacman --query "${PACKAGE_NAME}" 2> /dev/null \
+      | cut --field 2 --delimiter ' '
+  )
+
+  # need double --check argument to show modified files
+  local package_modified_files=( $(
+    pacman --query --check --check "${PACKAGE_NAME}" \
+      | grep '^backup file:' \
+      | cut --field 4 --delimiter ' ' \
+      | uniq
+  ) )
+
+  # OPTIMIZE: if it happens we have packages with many modified files
+  # we maybe better extract first a single time instead of doing for each file
+  local package_modified_file
+  for package_modified_file in ${package_modified_files}; do
+    echo "${package_modified_file}"
+    tar --extract --to-stdout \
+      --file /var/cache/pacman/pkg/${PACKAGE_NAME}-${package_version}-*.pkg.tar.xz \
+      "${package_modified_file/\//}" \
+      2> /dev/null \
+    | diff - "${package_modified_file}"
+    echo
+  done
+}
+
+
+parse_options() {
+  while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+      -h|--help)
+        usage
+        exit 0
+        ;;
+      *)
+        break 2
+        ;;
+    esac
+  done
+
+  PACKAGE_NAME="$1"
+}
+
+
+validate_options() {
+  if [[ -z "${PACKAGE_NAME}" ]]; then
+    error 'missing package name'
+  fi
+
+  if ! pacman --query "${PACKAGE_NAME}" &> /dev/null; then
+    error "invalid package name ${PACKAGE_NAME}"
+  fi
+}
+
+
+init_variables
+parse_options "$@"
+validate_options
+
+diff_package
diff --git a/zsh/scripts/tmux_env b/zsh/scripts/tmux_env
--- a/zsh/scripts/tmux_env
+++ b/zsh/scripts/tmux_env
@@ -1,20 +1,22 @@
 #!/usr/bin/env zsh
 
-# init variables
 COMMAND=${0:t}
-ENV_DIR_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/env/"
 
-AVAILABLE_TARGETS=( $(
-  ls "${ENV_DIR_PATH}"
-) )
-BACKGROUND=false
+init_variables() {
+  ENV_DIR_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/env/"
 
-TARGET=
-SESSIONS=
+  AVAILABLE_TARGETS=( $(
+    ls "${ENV_DIR_PATH}"
+  ) )
+  BACKGROUND=false
 
-# variables coming from env files
-HOST=localhost
-SOCKET=default
+  TARGET=
+  SESSIONS=
+
+  # variables coming from env files
+  HOST=localhost
+  SOCKET=default
+}
 
 
 usage() {
@@ -35,10 +37,9 @@ EOF
 
 
 error() {
-  if [[ -n "$1" ]]; then
-    echo "error: $1" >&2
-  fi
+  [[ -z "$1" ]] || echo "$1" >&2
   usage
+  exit 1
 }
 
 
@@ -138,44 +139,47 @@ start_target_tmux_env() {
 }
 
 
-# parse options
-while [[ "$#" -gt 0 ]]; do
-  case "$1" in
-    -b|--background)
-      BACKGROUND=true
-      shift
-      ;;
-    -h|--help)
-      usage
-      return 0
-      ;;
-    *)
-      break 2
-      ;;
-  esac
-done
+parse_options() {
+  while [[ "$#" -gt 0 ]]; do
+    case "$1" in
+      -b|--background)
+        BACKGROUND=true
+        shift
+        ;;
+      -h|--help)
+        usage
+        exit 0
+        ;;
+      *)
+        break 2
+        ;;
+    esac
+  done
 
-if [[ $# -eq 0 ]]; then
-  error 'missing target'
-  return 1
-fi
-
-TARGET="$1"
-SESSIONS=( ${@:2} )
-
-# validate target
-if ! (( ${AVAILABLE_TARGETS[(Ie)${TARGET}]} )); then
-  error "invalid target ${TARGET}"
-  return 1
-fi
-
-# validate target's sessions if present
-for session in ${SESSIONS}; do
-  if [[ ! -f "${ENV_DIR_PATH}/${TARGET}/${session}.sh" ]]; then
-    error "invalid target's session ${session}"
-    return 1
+  if [[ $# -eq 0 ]]; then
+    error 'missing target'
   fi
-done
 
+  TARGET="$1"
+  SESSIONS=( ${@:2} )
+}
+
+
+validate_options() {
+  if ! (( ${AVAILABLE_TARGETS[(Ie)${TARGET}]} )); then
+    error "invalid target ${TARGET}"
+  fi
+
+  for session in ${SESSIONS}; do
+    if [[ ! -f "${ENV_DIR_PATH}/${TARGET}/${session}.sh" ]]; then
+      error "invalid target's session ${session}"
+    fi
+  done
+}
+
+
+init_variables
+parse_options "$@"
+validate_options
 
 start_target_tmux_env
